### ISSUE TITLE
Trybuild fails to parse manifest when run under tarpaulin

### ISSUE THREAD

**Issue by CAD97** [dtolnay/trybuild#11]
Not that this changes reported coverage in any way (I'm fairly sure), but I thought it was interesting:

https://travis-ci.com/CAD97/generativity/builds/112686687#L861-L957

I'm not sure whether this is a trybuild issue or a tarpaulin issue, so I decided to start here. I don't have a linux box available to attempt further investigation.

**Comment by dtolnay** [comment]
Thanks! I can take a look later this week. That error would have come from:

https://github.com/dtolnay/trybuild/blob/2b79660aa67408fd35614c730f86f27b845a60a5/src/cargo.rs#L69-L80

where `raw_cargo()` is:

https://github.com/dtolnay/trybuild/blob/2b79660aa67408fd35614c730f86f27b845a60a5/src/cargo.rs#L9-L11

So whatever Cargo tarpaulin is running with does not produce recognizable output from `cargo metadata --format-version=1`.

**Comment by dtolnay** [comment]
It looks like when tarpaulin performs the build it sets `CARGO=/path/to/.cargo/bin/cargo-tarpaulin`. We run `$CARGO metadata --format-version=1` and it fails with:

```console
error: Found argument 'metadata' which wasn't expected, or isn't valid in this context

USAGE:
    cargo [SUBCOMMAND]

For more information try --help
```

because the cargo-tarpaulin binary predictably only implements a tarpaulin subcommand:

```console
$ /path/to/.cargo/bin/cargo-tarpaulin --help
cargo-tarpaulin version: 0.8.0
Daniel McKenna, <danielmckenna93@gmail.com>
Tool to analyse test coverage of cargo projects

USAGE:
    cargo [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    help         Prints this message or the help of the given subcommand(s)
    tarpaulin    Tool to analyse test coverage of cargo projects
```

To me this looks like an unintended consequence of how they set up the build using cargo-as-a-library [here](https://github.com/xd009642/tarpaulin/blob/0.8.0/src/lib.rs#L45-L102) in the same way that actual cargo would do it. I would recommend pursuing a fix in cargo-tarpaulin -- or at least I would want to understand why they must set CARGO this way.

I'll close for now, but we can think about workarounds if they aren't able to make a fix on their end.
