### ISSUE TITLE
Summarize differences with compiletest-rs?

### ISSUE THREAD

**Issue by dekellum** [dtolnay/trybuild#13]
I currently have an unmerged branch in one project (tao-log) using compiletest-rs for the same use case.  Its unmerged because compiletest-rs appears, in my very limited experience, to be nightly-only and quite sensitive to ongoing changes in the rustc nightly builds. 

Would it be reasonable to briefly summarize differences in design, approach or goals with trybuild, either here, or for example in  a _Prior Art_ or _Alternatives_ section in the README?

**Comment by dtolnay** [comment]
I got pretty unhappy with the design of compiletest and with the way the library is maintained. This library does the small set of things that I want from an error message testing library without all the downsides of the compiletest crate; hopefully it is useful to others too.

#### What's wrong with compiletest:

- The library is closely coupled to the upstream compiletest in rust-lang/rust so it is perpetually broken -- https://github.com/laumann/compiletest-rs/issues/18 https://github.com/laumann/compiletest-rs/issues/33 https://github.com/laumann/compiletest-rs/issues/44 https://github.com/laumann/compiletest-rs/pull/47 https://github.com/laumann/compiletest-rs/pull/49 https://github.com/laumann/compiletest-rs/pull/50 https://github.com/laumann/compiletest-rs/issues/51 https://github.com/laumann/compiletest-rs/pull/61 https://github.com/laumann/compiletest-rs/pull/63 https://github.com/laumann/compiletest-rs/issues/64 https://github.com/laumann/compiletest-rs/pull/75 https://github.com/laumann/compiletest-rs/issues/86 https://github.com/laumann/compiletest-rs/pull/93 https://github.com/laumann/compiletest-rs/issues/98 https://github.com/laumann/compiletest-rs/issues/103 https://github.com/laumann/compiletest-rs/issues/118 https://github.com/laumann/compiletest-rs/issues/129 https://github.com/laumann/compiletest-rs/issues/131 https://github.com/laumann/compiletest-rs/issues/137 https://github.com/laumann/compiletest-rs/issues/159 https://github.com/laumann/compiletest-rs/issues/166.

- They recently added a "stable" flag which turns off the use of nightly compiler features so that you can use it in a way that isn't broken by nightly compiler churn, except the "stable" mode is perpetually broken too, pretty much just as frequently -- https://github.com/laumann/compiletest-rs/issues/133 https://github.com/laumann/compiletest-rs/issues/164. This is when I gave up on the crate.

- If there were a good reason that the crate needed to use nightly features in order to provide a good user experience, maybe that would be okay. But depressingly there isn't a reason. The only code requiring nightly in the crate is for a feature that nobody even uses -- https://github.com/laumann/compiletest-rs/issues/135.

- If you are lucky enough to get the compiletest crate itself to compile, writing a test with it requires you to handwrite a rustc invocation command line which is either [complicated](https://github.com/dekellum/tao-log/blob/a0464b9780ee942f598ededa891e5be4a28b3e02/test_compile_errors/tests/tests.rs) or [more complicated](https://github.com/taiki-e/auto_enums/blob/33629458be04e09865563b619961375c40a389db/test_suite/tests/compile-test.rs) or [super complicated](https://github.com/antifuchs/nonzero_ext/blob/feb9f1b9db8f89b00835843c06e7ecea757bdcd8/tests/compiletest.rs) or [ridiculous](https://github.com/SergioBenitez/Rocket-Azure/blob/533f991df5507492581cd3ac7c166d1a7d7a527f/contrib/codegen/tests/compile-test.rs) depending on what dependencies are involved.

- Once you get all the `-L` and `--extern` flags lined up in a way that sometimes works, your tests will randomly fail in confusing ways depending on the state of the `target` directory -- https://github.com/laumann/compiletest-rs/issues/62 https://github.com/laumann/compiletest-rs/issues/78 https://github.com/laumann/compiletest-rs/issues/101 https://github.com/laumann/compiletest-rs/issues/114 https://github.com/rust-lang/rust-clippy/issues/3643 https://github.com/rust-lang/rust-clippy/issues/4015 https://github.com/alexcrichton/futures-await/issues/81 https://github.com/lpc-rs/lpc8xx-hal/issues/105.

#### Differences in trybuild:

- We invoke cargo instead of rustc. No handwritten rustc flags, no "multiple matching crates" errors, all dev-dependencies immediately accessible, no unstable libtest, no rustc_private, no nightly features.

**Comment by dekellum** [comment]
So I wasn't alone in my compiletest-rs stability concerns, but you've given a lot more detail than I was aware of, thanks.  I found converting my compile tests to trybuild straight forward:

https://github.com/dekellum/tao-log/compare/2efb701a..70889823

...and as a bonus I can now enable my tests on stable rust 1.35.0 and nightly. (Before 1.35.0, the rustc error messages under test are different.)   Other minor differences I'll note from the fresh conversion experience:

* trybuild uses separate `*.stderr` files for comparing compiler output, instead of source inline `//~ ERROR` style comments as used in rust/src/tools/compiletest and compiletest-rs.  The _workflow_ feature of writing the actual compiler output to compatible files in a _wip_ directory makes this much easier than guessing at the supported comment syntax of the former. 

* trybuild compile tests expect an `fn main` (It presumably compiles using `--bin` or equivalent.  Without this, an extra "error[E0601]: `main` function not found in crate `$CRATE`" will be recorded.)

So perhaps rust/src/tools/compiletest should also be mentioned in a _Prior Art_ type summary?  
Compiling using cargo seems to be a big stability and ease of use advantage for trybuild. Thanks for sharing this work!

**Comment by aldanor** [comment]
@dtolnay That's a pretty good description; would it make sense to list some of that directly in the readme? I believe most people who've stumbled upon this crate would be coming directly from compiletest-rs.
