### ISSUE TITLE
Support for pass tests via `cargo test`

### ISSUE THREAD

**Issue by vobradovich** [dtolnay/trybuild#272]
When generating code, it may be convenient not only to check if the program is successfully run via 'cargo run', but also if it passes tests via 'cargo test'.

A new method is proposed ` t.pass_test(“ui/some_file_with_tests.rs”);` 

Already discussed in https://github.com/dtolnay/trybuild/issues/231. but may be revised.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. As in #231, you may want to pursue making a more fully featured diagnostic testing library that can do this.

**Comment by robamu** [comment]
This seems really useful and there is already existing PR as well: https://github.com/dtolnay/trybuild/pull/273 ! I am looking into improving an existing macro library which only has unit-tests. I don' t want to convert all the unittest back to one main function because I like the granular nature of the unit-tests.
