### ISSUE TITLE
Support copying files into the test package

### ISSUE THREAD

**Issue by upsuper** [dtolnay/trybuild#95]
Sometimes we want to implement proc macros which can read from file in the package directory, usually relative to the manifest path (because there is no way to get the path of source code for proc macro). There doesn't seem to be any easy way to test such functionality with `trybuild` currently.

It would be good to have some mechanism to allow copying files into the test package, either by adding a method to expose the directory of the test package, or by adding a method to specify files to copy to. I guess the latter is probably preferable.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. Reading external files is a pretty uncommon use case (maybe 1% of proc macros) and this is a crate that I would prefer to keep focused on the 90% use case rather than aiming to be everything to everyone.

It would be reasonable to build support for copying files in a fork of trybuild, or in a new crate that's focused on macro testing in more generality.
